#!/usr/bin/env node
'use strict';
const fs=require('fs');
const path=require('path');
const zlib=require('zlib');
const TEMPLATE_ROOT=path.join(__dirname,'templates');
const OUT_ROOT=path.resolve(process.cwd(),'CargoSort_3D');
const ZIP_PATH=path.resolve(process.cwd(),'CargoSort_3D_Design_Package.zip');
function crc32(buf){let crc=0xffffffff;for(const b of buf){crc^=b;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
function dosDateTime(date=new Date()){const y=Math.max(1980,date.getFullYear());return{time:(date.getHours()<<11)|(date.getMinutes()<<5)|(date.getSeconds()>>1),date:((y-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate()};}
function copyTree(src,dst){let count=0;for(const e of fs.readdirSync(src,{withFileTypes:true})){const a=path.join(src,e.name),b=path.join(dst,e.name);if(e.isDirectory()){fs.mkdirSync(b,{recursive:true});count+=copyTree(a,b);}else{fs.mkdirSync(path.dirname(b),{recursive:true});fs.copyFileSync(a,b);count++;}}return count;}
function collect(dir,base='CargoSort_3D'){let out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,e.name),name=path.posix.join(base,e.name);out=e.isDirectory()?out.concat(collect(full,name)):out.concat({full,name});}return out;}
function makeZip(){const localParts=[],centralParts=[];let offset=0,entries=0;for(const e of collect(OUT_ROOT)){const data=fs.readFileSync(e.full),packed=zlib.deflateRawSync(data,{level:9}),name=Buffer.from(e.name,'utf8'),crc=crc32(data),dt=dosDateTime(fs.statSync(e.full).mtime);const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0x0800,6);local.writeUInt16LE(8,8);local.writeUInt16LE(dt.time,10);local.writeUInt16LE(dt.date,12);local.writeUInt32LE(crc,14);local.writeUInt32LE(packed.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(name.length,26);localParts.push(local,name,packed);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50,0);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x0800,8);c.writeUInt16LE(8,10);c.writeUInt16LE(dt.time,12);c.writeUInt16LE(dt.date,14);c.writeUInt32LE(crc,16);c.writeUInt32LE(packed.length,20);c.writeUInt32LE(data.length,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE(offset,42);centralParts.push(c,name);offset+=local.length+name.length+packed.length;entries++;}const central=Buffer.concat(centralParts),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(entries,8);end.writeUInt16LE(entries,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(offset,16);const zip=Buffer.concat([...localParts,central,end]);fs.writeFileSync(ZIP_PATH,zip);return zip.length;}
function validate(){const required=['01_Design_System/ColorPalette.json','01_Design_System/TypographyAndUI.json','02_Shaders_And_VFX/ItemHighlight.shader','02_Shaders_And_VFX/ButtonLightSweep.shader','02_Shaders_And_VFX/MatchConfettiVFX.json','03_Core_3D_Logic/CameraSetup.cs','03_Core_3D_Logic/DragAndDrop3D.cs','03_Core_3D_Logic/ComboFXManager.cs','04_UI_And_Screens/WorldMap3DNodes.cs','04_UI_And_Screens/LevelClearModal.cs','README.md'];for(const rel of required){if(!fs.existsSync(path.join(OUT_ROOT,rel)))throw new Error('Missing output: '+rel);}return required.length;}
try{if(!fs.existsSync(TEMPLATE_ROOT))throw new Error('Template root not found: '+TEMPLATE_ROOT);fs.rmSync(OUT_ROOT,{recursive:true,force:true});fs.rmSync(ZIP_PATH,{force:true});fs.mkdirSync(OUT_ROOT,{recursive:true});const copied=copyTree(TEMPLATE_ROOT,OUT_ROOT),required=validate(),bytes=makeZip();console.log(`[CargoSort3D] OK: copied=${copied}, required=${required}, zip=${(bytes/1024).toFixed(1)} KiB`);console.log(ZIP_PATH);}catch(e){console.error('[CargoSort3D] BUILD FAILED:',e.stack||e);process.exit(1);}
