org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configureondemand=false
org.gradle.workers.max=1
kotlin.incremental=false
kotlin.incremental.java=false
kotlin.incremental.useClasspathSnapshot=false
kotlin.caching.enabled=false
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.enabled=false
